import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppThemeProvider } from "./AppThemeProvider";
import Nav from "./components/theme/Navbar";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Harry-Potter-Web-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <AppThemeProvider>
          <Nav />
          {children}
        </AppThemeProvider>
      </body>
    </html>
  );
}
